name: "Build"

on:
  workflow_dispatch:
    inputs:
      run_update:
        type: boolean
        default: false
        required: false
        description: "Tries to update the repository like maven/gradle wrapper and maven properties"
      run_test:
        type: boolean
        default: true
        required: false
        description: "Runs maven/gradle tests"
      run_deploy:
        type: choice
        required: false
        default: "disabled"
        description: "version increment (Main branch with changes only) [major, minor, patch, rc, disabled]"
        options:
          - "disabled"
          - "major"
          - "minor"
          - "patch"
          - "rc"
      ref:
        type: string
        required: false
        description: "[ref] e.g. branch, tag or commit to checkout [default: github_ref_name || github_head_ref ]"

jobs:
  builld:
    uses: ./.github/workflows/java_build.yml
    with:
      ref: ${{ github.event.inputs.ref || github.ref || github.ref_name || github.head_ref }}
      run_update: ${{ inputs.run_update }}
      run_test: ${{ inputs.run_test }}
      run_deploy: ${{ inputs.run_deploy }}
    secrets: inherit
