name: "Daily"

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  builld:
    uses: ./.github/workflows/java_build.yml
    with:
      run_update: true
      run_test: true
      run_deploy: patch
    secrets: inherit
